koka-3.2.2: unregistering (local file changes: src/Core/FlowAnalysis/Full/DMCFAR/Syntax.hs)
koka> build (lib + exe) with ghc-9.6.6
Preprocessing library for koka-3.2.2..
Building library for koka-3.2.2..
[126 of 143] Compiling Core.FlowAnalysis.Full.DMCFAR.Syntax [Source file changed]
[140 of 143] Compiling Compile.Build [Core.FlowAnalysis.Full.DMCFAR.Syntax changed]
Warning: The following header files listed in the main library's c-sources
will not be used: src/Platform/cpp/Platform/cconsole.h.
Header files should be in the 'include' or 'install-include' stanza.
See https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-includes
Preprocessing executable 'koka' for koka-3.2.2..
Building executable 'koka' for koka-3.2.2..
[18 of 18] Linking .stack-work/dist/x86_64-linux/ghc-9.6.6/build/koka/koka [Library changed]
koka> copy/register
Installing library in /home/tim/koka/.stack-work/install/x86_64-linux/caa2c2a0c9eec164a22324b7d83105503be009c866f84849897f47c50a8aa47d/9.6.6/lib/x86_64-linux-ghc-9.6.6/koka-3.2.2-8GBEfjISoFBMgz1sr3wgW
Installing executable koka in /home/tim/koka/.stack-work/install/x86_64-linux/caa2c2a0c9eec164a22324b7d83105503be009c866f84849897f47c50a8aa47d/9.6.6/bin
Registering library for koka-3.2.2..
Failed to compile analysis/benchmarks/benchmarks.kk
