]4;0;?\[6nkcfa,analysis/benchmarks/suite/nondet/nondet-context,0,50,1,107,9,1.0,1.0,1.0,1.0,0.002379,0.001691,0.00195
kcfa,analysis/benchmarks/suite/nondet/nondet-discard,0,50,1,84,7,1.0,1.0,1.0,1.0,0.001072,0.001031,0.001031
parse   : .../std/core/types.kk
parse   : .../std/core/unsafe.kk
parse   : .../std/core/hnd.kk
parse   : .../std/core/exn.kk
parse   : .../std/core/undiv.kk
parse   : .../std/core/bool.kk
parse   : .../std/core/int.kk
parse   : .../std/core/vector.kk
parse   : .../std/core/sslice.kk
parse   : .../std/core/string.kk
parse   : .../std/core/list.kk
parse   : .../std/core/maybe.kk
parse   : .../std/core/char.kk
parse   : .../std/core/order.kk
parse   : .../std/core/tuple.kk
parse   : .../std/core/maybe2.kk
parse   : .../std/core/show.kk
parse   : .../std/core/either.kk
parse   : .../std/core/console.kk
parse   : .../std/core/delayed.kk
parse   : .../std/core/lazy.kk
parse   : .../std/core/debug.kk
parse   : .../std/core.kk
parse   : .../analysis/benchmarks/suite/nondet.kk
check   : std/core/types
check   : std/core/undiv
check   : std/core/lazy
check   : std/core/bool
check   : std/core/unsafe
check   : std/core/hnd
check   : std/core/int
check   : std/core/order
check   : std/core/char
check   : std/core/exn
check   : std/core/tuple
check   : std/core/delayed
check   : std/core/either
check   : std/core/vector
check   : std/core/maybe
check   : std/core/maybe2
check   : std/core/string
check   : std/core/sslice
check   : std/core/list
check   : std/core/show
check   : std/core/console
check   : std/core/debug
check   : std/core
check   : analysis/benchmarks/suite/nondet
kcfa,analysis/benchmarks/suite/nondet/nondet-nested,0,50,0,675,17,5.214814814814815,9.647058823529411,1.0,1.5955882352941178,1.458424,1.35852,1.356842
kcfa,analysis/benchmarks/suite/nondet/nondet-simple,0,50,1,92,7,1.0,1.0,1.0,1.0,0.001206,0.001061,0.000739
linking : analysis/benchmarks/suite/nondet/@main
compile : kklib from: /Users/timwhiting/koka/kklib
created : .koka/v3.2.3/clang-debug-1e5359/analysis_benchmarks_suite_nondet__main
