koka-3.2.3: unregistering (local file changes: src/Core/FlowAnalysis/Full/DMCFA/Syntax.hs)
koka> build (lib + exe) with ghc-9.6.6
Preprocessing library for koka-3.2.3..
Building library for koka-3.2.3..
[127 of 141] Compiling Core.FlowAnalysis.Full.DMCFA.Syntax [Source file changed]
Warning: The following header files listed in the main library's c-sources
will not be used: src/Platform/cpp/Platform/cconsole.h.
Header files should be in the 'include' or 'install-include' stanza.
See https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-includes
Preprocessing executable 'koka' for koka-3.2.3..
Building executable 'koka' for koka-3.2.3..
[18 of 18] Linking .stack-work/dist/aarch64-osx/ghc-9.6.6/build/koka/koka [Library changed]
koka> copy/register
Installing library in /Users/timwhiting/koka/.stack-work/install/aarch64-osx/50e7567ab93459510bfd412b9898f4e9df3111e36f9d2dfd4eb8cba51d1770ee/9.6.6/lib/aarch64-osx-ghc-9.6.6/koka-3.2.3-JKPkVdIR1OY3NjAC7CLiJ8
Installing executable koka in /Users/timwhiting/koka/.stack-work/install/aarch64-osx/50e7567ab93459510bfd412b9898f4e9df3111e36f9d2dfd4eb8cba51d1770ee/9.6.6/bin
Registering library for koka-3.2.3..
dmcfae,analysis/benchmarks/handlers/scoped/example1,40,40,1,1257,145,1.0,1.0,1.0,1.0,0.077635,0.076776,0.076417
dmcfae,analysis/benchmarks/handlers/scoped/example2,40,40,1,2498,626,1.0,1.0,1.0,1.0,0.605084,0.593554,0.592162
dmcfae,analysis/benchmarks/handlers/scoped/example3,40,40,1,2525,596,1.0,1.0,1.0,1.0,0.492727,0.48395,0.482619
dmcfae,analysis/benchmarks/handlers/scoped/example4,40,40,1,431,64,1.0,1.0,1.0,1.0,0.027308,0.027001,0.026999
dmcfae,analysis/benchmarks/handlers/scoped/example5,40,40,0,16553,4959,1.0029601884854709,1.0014115749142973,1.0,1.0112294006125127,6.493968,6.47488,6.479909
