name: libuv

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  ffigen:
    path: '../koka-community/native/pkgs/ffigen'
  lints: ^2.0.1

ffigen:
  name: libuv
  ffi-native:
    assetId: "c { vcpkg=\"libuv\" }\n\nextern import\n  c header-file \"third-party/uv.h\""
  description: Bindings to `libuv.h`.
  output: 'lib/uv/generated.kk'
  generate-compound-member-accessors: false
  compiler-opts:
    - '-I./lib/uv/third-party/'
    - '-I/usr/local/opt/llvm/lib/clang/18/include'
  headers:
    entry-points:
      - 'lib/uv/third-party/uv.h'
      - 'lib/uv/third-party/uv/version.h'
      - 'lib/uv/third-party/uv/errno.h'
    include-directives:
      - 'lib/uv/third-party/uv.h'
      - 'lib/uv/third-party/uv/*'
  compiler-opts-automatic:
    macos:
      include-c-standard-library: false
  preamble: |
    // Copyright (c) 2024, the Koka authors. All rights reserved. 
    // Use of this source code is governed by a
    // MIT-style license that can be found in the LICENSE file.
  functions:
    exclude:
      - (-)+.*
      - uv_thread_getpriority
      - uv_thread_setpriority
      - uv_utf16_length_as_wtf8
      - uv_utf16_to_wtf8
      - uv_wtf8_length_as_utf16
      - uv_wtf8_to_utf16
    rename:
      '-(.*)': '$1'
  structs:
    exclude:
      - (-)+.*
    rename:
      'uv--(.*)' : 'uv-$1'
      '-*(.*)': '$1'
    member-rename:
      '.*':
        '-*(.*)': '$1'
    dependency-only: opaque
  enums:
    exclude:
      - (-)+.*
    rename:
      'uv--(.*)' : 'uv-$1'
      '-*(.*)': '$1'
  unions:
    exclude:
      - (-)+.*
    rename:
      'uv--(.*)' : 'uv-$1'
      '-*(.*)': '$1'
  globals:
    exclude:
      - (-)+.*
    rename:
      'uv--(.*)' : 'uv-$1'
      '-*(.*)': '$1'
  macros:
    exclude:
      - (-)+.*
    rename:
      'uv--(.*)' : 'uv-$1'
      '-*(.*)': '$1'
  typedefs:
    exclude:
      - (-)+.*
    rename:
      'uv--(.*)' : 'uv-$1'
      '-*(.*)': '$1'
