on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

name: bundle
jobs:
  build:
    name: Bundle Koka
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macOS 13 is Intel based, later versions are arm64
        # we build on the oldest ubuntu for better binary compatibility.
        os: [window-latest, ubuntu-20.04, ubuntu-22.04-arm, macOS-13, macOS-15]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Set up stack and cache dependencies: https://github.com/freckle/stack-action (MIT license)
      - uses: freckle/stack-action@v5
        with:
          test: false
          stack-build-arguments: ""
          cache-save-always: true

      - name: Build
        run: stack build

      # Cache setup for vcpkg (https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache)
      - name: Setup vcpkg cache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Bundle
        run: |
          stack exec koka -- -e -O2 util/bundle

      # Create a release https://github.com/softprops/action-gh-release (MIT license)
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with: # support/vscode/koka.language-koka/*.vsix
      #     files: |
      #       bundle/**/*.tar.gz
      #       bundle/**/*.vsix
      #       util/install.bat
      #       util/install.sh
      #     make_latest: true