name: Build Koka and Publish release
on:
  push:
    tags: [v*]
    paths: ["src/**", "lib/**", "samples/**", "util/**"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_release:
    name: Koka build extension
    runs-on: ubuntu-latest
    container: 
      image: whitingta/koka:latest
    steps:
      - name: Setup folders
        run: |
          mkdir -p /build/koka
          mkdir -p /build/koka/test/bench
          mkdir -p /build/koka/test/bench/build
      - name: Build and Install Koka
        working-directory: /build/koka
        run: |
          # Koka
          stack build koka
          stack run koka -- -e util/bundle -- --postfix=docker --vcpkg=~/vcpkg
          util/install.sh -f -b bundle/${{ github.ref }}/koka-docker.tar.gz
      - name: Build Benchmarks
        working-directory: /build/koka/test/bench/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release
          eval $(opam env) && cmake --build .
      - name: Run Benchmarks and tests
        working-directory: /build/koka/test/bench
        run: |
          stack run koka -e bench
          stack test
      - name: Build Extension
        working-directory: /build/koka/support/vscode/koka.language-koka
        run: |
          npm install
          npm run package
      - name: Publish Extension
        uses: actions/upload-artifact@v2
        with:
          name: koka-language-koka-${{ github.ref }}
          path: support/vscode/koka.language-koka/koka-language-koka-${{ github.ref }}.vsix
      - name: Publish Linux Binary
        uses: actions/upload-artifact@v2
        with:
          name: koka-${{ github.ref }}-linux
          path: /build/koka/bundle/${{ github.ref }}/koka-docker.tar.gz
      # TODO: OSX and Windows, just do a release, no tests or benchmarks
